version: '3'
services:
  back:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  db:
    image: mongo:latest
    # ports:
      # - "27017:27017" # This config is to expose the port to the host machine. 
      # We could delete this line and the app would still be able to connect to the db container
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
  